[workspace]
members = [
  "apps/gateway",
  "apps/auth",
  "apps/tokens-async",
  "apps/tokens",
  "apps/oauth2",
  "apps/integrations",
  "apps/passport",

  "libs/config",
  "libs/db",
  "libs/grpc",
  "libs/nats",
  "libs/log",
  "libs/utils",
]

resolver = "2"
