[workspace]
members = [
  "apps/gateway",
  "apps/auth",
  "apps/tokens",
  "apps/oauth2",

  "libs/config",
  "libs/db",
  "libs/grpc",
  "libs/log",
  "libs/utils",
]

resolver = "2"
