version: "3"

services:
  nats:
    image: "nats:latest"
    command: ["-js"]

  integrations:
    container_name: apps-integrations
    build:
      context: '.'
      dockerfile: "apps/integrations/Dockerfile"
    ports:
      - "3150:80"
    env_file:
      - .env.prod
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:14-alpine
#    volumes:
#      - makoto_db:/var/lib/postgresql/makoto/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "54321:5432"

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: "makoto.web3@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "postgres"
        PGADMIN_CONFIG_SERVER_MODE: "False"
#      volumes:
#        - pgadmin_data:/var/lib/pgadmin
      ports:
        - "5050:80"
      restart: unless-stopped
      logging:
        driver: none