version: "3"

dotenv: [.env]

tasks:
  db:migrate:
    cmds:
      - go run libs/db/main.go migrate
      - cd libs/db && sea-orm-cli generate entity -u $DATABASE_URL -o src/models

  grpc:
    cmds:
      - cd libs/grpc && cargo run
      - cd libs/grpc && pnpm exec protoc -I=protos --ts_out=dist --ts_opt=generate_dependencies,eslint_disable,ts_nocheck,output_javascript protos/*.proto
      - cd libs/grpc && pnpm exec protoc -I protos --ts_out=dist --ts_opt=generate_dependencies,eslint_disable,ts_nocheck,output_javascript protos/api.proto
      - cd libs/grpc && pnpm ts

  cli:
    cmds:
      - cargo run -p cli -- {{.CLI_ARGS}}