version: "3"

dotenv: [.env]

tasks:
  db:migrate:
    cmds:
      - go run libs/db/main.go migrate
      - cd libs/db && sea-orm-cli generate entity -u $DATABASE_URL -o src/models

  grpc:
    cmds:
      - cd libs/grpc && cargo run
      - cd libs/grpc && pnpm exec protoc -I=protos --ts_out=dist --ts_opt=generate_dependencies,eslint_disable,ts_nocheck,output_javascript protos/api/*.proto
      - cd libs/grpc && pnpm exec protoc -I protos --ts_out=dist --ts_opt=generate_dependencies,eslint_disable,ts_nocheck,output_javascript protos/api.proto
      - cd libs/grpc && pnpm ts

  grpc:go:
    cmds:
      - cd libs/grpc && pnpm exec protoc --go_out=gen --go-grpc_out=gen --experimental_allow_proto3_optional --go_opt=paths=source_relative  --go-grpc_opt=paths=source_relative --proto_path=protos protos/api/mailer.proto
#      - cd libs/grpc && pnpm exec protoc --go_out=gen --go-grpc_out=gen --experimental_allow_proto3_optional --twirp_out=gen --go_opt=paths=source_relative --twirp_opt=paths=source_relative --go-grpc_opt=paths=source_relative --proto_path=protos protos/api.proto

  # go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

  cli:
    cmds:
      - cargo run -p cli -- {{.CLI_ARGS}}