//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "languages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_languages::Entity")]
    UserLanguages,
}

impl Related<super::user_languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLanguages.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_languages::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_languages::Relation::Languages.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
