//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique)]
    pub author_id: Uuid,
    pub images: Option<Vec<String>>,
    pub views: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::post_reports::Entity")]
    PostReports,
    #[sea_orm(has_many = "super::user_hidden_posts::Entity")]
    UserHiddenPosts,
    #[sea_orm(has_many = "super::user_liked_posts::Entity")]
    UserLikedPosts,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::post_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostReports.def()
    }
}

impl Related<super::user_hidden_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserHiddenPosts.def()
    }
}

impl Related<super::user_liked_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLikedPosts.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
