//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::languages::Entity as Languages;
pub use super::user_blocked::Entity as UserBlocked;
pub use super::user_credentials::Entity as UserCredentials;
pub use super::user_followers::Entity as UserFollowers;
pub use super::user_friends::Entity as UserFriends;
pub use super::user_integrations::Entity as UserIntegrations;
pub use super::user_languages::Entity as UserLanguages;
pub use super::user_tokens::Entity as UserTokens;
pub use super::users::Entity as Users;
