//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub location: Option<String>,
    pub birthday: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pseudonym: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub picture: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::comments::Entity")]
    Comments,
    #[sea_orm(has_one = "super::posts::Entity")]
    Posts,
    #[sea_orm(
        belongs_to = "super::user_credentials::Entity",
        from = "Column::UserId",
        to = "super::user_credentials::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserCredentials,
    #[sea_orm(has_many = "super::user_hidden_posts::Entity")]
    UserHiddenPosts,
    #[sea_orm(has_many = "super::user_languages::Entity")]
    UserLanguages,
    #[sea_orm(has_many = "super::user_liked_comments::Entity")]
    UserLikedComments,
    #[sea_orm(has_many = "super::user_liked_posts::Entity")]
    UserLikedPosts,
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Posts.def()
    }
}

impl Related<super::user_credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCredentials.def()
    }
}

impl Related<super::user_hidden_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserHiddenPosts.def()
    }
}

impl Related<super::user_languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLanguages.def()
    }
}

impl Related<super::user_liked_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLikedComments.def()
    }
}

impl Related<super::user_liked_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLikedPosts.def()
    }
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_liked_comments::Relation::Comments.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_liked_comments::Relation::Users.def().rev())
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_languages::Relation::Languages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_languages::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
