//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_languages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub language_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::languages::Entity",
        from = "Column::LanguageId",
        to = "super::languages::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Languages,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserUserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Languages.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
