//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_informations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub location: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub birthday: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pseudonym: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_credentials::Entity",
        from = "Column::UserId",
        to = "super::user_credentials::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserCredentials,
    #[sea_orm(has_many = "super::user_languages::Entity")]
    UserLanguages,
}

impl Related<super::user_credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCredentials.def()
    }
}

impl Related<super::user_languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLanguages.def()
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_languages::Relation::Languages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::user_languages::Relation::UserInformations
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
